# Server configuration
server:
  address: ":8080"
  read_timeout: "15s"
  write_timeout: "15s"
  idle_timeout: "60s"

# Database configuration
database:
  url: "mongodb://jobuser:jobpassword@localhost:27017"
  name: "jobscraper"
  max_pool_size: 100
  min_pool_size: 5

# Scraper configuration
scraper:
  default_pages: 1

# Logging configuration
log:
  level: "info"
  format: "json"