version: '3.8'

services:
  mongodb:
    image: mongo:5.0
    container_name: jobscraper_mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=jobuser
      - MONGO_INITDB_ROOT_PASSWORD=jobpassword
      - MONGO_INITDB_DATABASE=jobscraper
    volumes:
      - mongodb_data:/data/db
    networks:
      - jobscraper_network
    restart: unless-stopped
    logging:
      driver: "none"

  jobscraper:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jobscraper_app
    depends_on:
      - mongodb
    networks:
      - jobscraper_network
    ports:
      - "8000:8000"
    restart: unless-stopped

volumes:
  mongodb_data:
    name: jobscraper_mongodb_data

networks:
  jobscraper_network:
    name: jobscraper_network
    driver: bridge