// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/jobs": {
            "get": {
                "description": "Get a list of jobs",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "jobScraper"
                ],
                "summary": "Get jobs",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/scraper.Job"
                            }
                        }
                    }
                }
            }
        },
        "/scrape": {
            "post": {
                "description": "Start scraping jobs based on the provided configuration",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "jobScraper"
                ],
                "summary": "Start scraping",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Job Title",
                        "name": "jobTitle",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Country",
                        "name": "country",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Number of Pages",
                        "name": "pages",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "indeed",
                            "linkedin"
                        ],
                        "type": "string",
                        "description": "Source of job listings (indeed or linkedin)",
                        "name": "source",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Scraping started",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "scraper.Job": {
            "type": "object",
            "properties": {
                "company": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "location": {
                    "type": "string"
                },
                "platform_job_id": {
                    "type": "string"
                },
                "source": {
                    "$ref": "#/definitions/scraper.ScraperType"
                },
                "summary": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "scraper.ScraperType": {
            "type": "string",
            "enum": [
                "indeed",
                "linkedin"
            ],
            "x-enum-varnames": [
                "Indeed",
                "LinkedIn"
            ]
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Job Scraper API",
	Description:      "This is a job scraper application.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
