basePath: /api/v1
definitions:
  scraper.Job:
    properties:
      company:
        type: string
      createdAt:
        type: string
      id:
        type: string
      location:
        type: string
      platform_job_id:
        type: string
      summary:
        type: string
      title:
        type: string
      url:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a job scraper application.
  termsOfService: http://swagger.io/terms/
  title: Job Scraper API
  version: "1.0"
paths:
  /jobs:
    get:
      consumes:
      - application/json
      description: Get a list of jobs
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/scraper.Job'
            type: array
      summary: Get jobs
      tags:
      - jobs
  /scrape:
    post:
      consumes:
      - application/json
      description: Start scraping jobs based on the provided configuration
      parameters:
      - description: Job Title
        in: query
        name: jobTitle
        required: true
        type: string
      - description: Country
        in: query
        name: country
        required: true
        type: string
      - description: Number of Pages
        in: query
        name: pages
        type: integer
      produces:
      - application/json
      responses:
        "202":
          description: Scraping started
          schema:
            type: string
      summary: Start scraping
      tags:
      - scrape
swagger: "2.0"
