basePath: /api/v1
definitions:
  scraper.Job:
    properties:
      company:
        type: string
      createdAt:
        type: string
      id:
        type: string
      location:
        type: string
      platform_job_id:
        type: string
      source:
        $ref: '#/definitions/scraper.ScraperType'
      summary:
        type: string
      title:
        type: string
      url:
        type: string
    type: object
  scraper.ScraperType:
    enum:
    - indeed
    - linkedin
    type: string
    x-enum-varnames:
    - Indeed
    - LinkedIn
host: localhost:8080
info:
  contact: {}
  description: This is a job scraper application.
  termsOfService: http://swagger.io/terms/
  title: Job Scraper API
  version: "1.0"
paths:
  /jobs:
    get:
      consumes:
      - application/json
      description: Get a list of jobs
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/scraper.Job'
            type: array
      summary: Get jobs
      tags:
      - jobScraper
  /scrape:
    post:
      description: Start scraping jobs based on the provided configuration
      parameters:
      - description: Job Title
        in: query
        name: jobTitle
        required: true
        type: string
      - description: Country
        in: query
        name: country
        required: true
        type: string
      - default: 1
        description: Number of Pages
        in: query
        name: pages
        type: integer
      - description: Source of job listings (indeed or linkedin)
        enum:
        - indeed
        - linkedin
        in: query
        name: source
        required: true
        type: string
      produces:
      - application/json
      responses:
        "202":
          description: Scraping started
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      summary: Start scraping
      tags:
      - jobScraper
swagger: "2.0"
